version: "3.9"
services:
  backend:
    env_file: ${ENV_FILE}
    build:
      context: ./
      dockerfile: ${DOCKERFILE}
      args:
        - WORK_DIR=${WORK_DIR}
        - PORT=${APPLICATION_PORT}
    ports:
      - ${DOCKER_HOST_APPLICATION_PORT}:${APPLICATION_PORT}
    volumes:
      - './src:${WORK_DIR}/src'
      - './tsconfig.json:${WORK_DIR}/tsconfig.json'
      - './tsconfig.build.json:${WORK_DIR}/tsconfig.build.json'
      - './.eslintrc.js:${WORK_DIR}/.eslintrc.js'
      - './.eslintignore:${WORK_DIR}/.eslintignore'
      - './.prettierrc:${WORK_DIR}/.prettierrc'
      - './nest-cli.json:${WORK_DIR}/nest-cli.json'
    entrypoint: ["npm", "run", "start:dev"]
